from __future__ import annotations

RISK_THRESHOLD_CRITICAL = 90
RISK_THRESHOLD_HIGH = 50
RISK_THRESHOLD_MEDIUM = 20

RISK_CURL_PIPE_EXEC = 100
RISK_WGET_PIPE_EXEC = 100
RISK_FIND_EXEC_RM_COMPOSITION = 80
RISK_SUDO_RM_RF = 100
RISK_GIT_RESET_CLEAN = 90
RISK_ECHO_REDIRECT = 20
RISK_DEEP_NESTING = 50
RISK_COMMAND_SUBSTITUTION = 10

RISK_FIND_DELETE = 50
RISK_RM_BASE = 50
RISK_RM_FORCE_RECURSIVE = 50
RISK_GIT_STATE_CHANGE = 30
RISK_GIT_CLEAN_FLAGS = 20
RISK_PKG_INSTALL = 20
RISK_CURL_WGET = 20
RISK_BASH_C = 40
RISK_SUDO = 80
RISK_MV_CP_FORCE = 20
RISK_MV_CP_BASE = 10
RISK_CHMOD_RECURSIVE = 25
RISK_CHMOD_CHOWN_BASE = 10
RISK_MAKE = 10
RISK_SED_INPLACE = 30
RISK_TAR_EXTRACT = 10
RISK_UNZIP = 10
RISK_INLINE_CODE = 20
RISK_SSH_SCP = 20
RISK_SSH_REMOTE_CMD = 20
RISK_DOCKER_RUN = 20
RISK_DOCKER_EXEC = 15
RISK_DOCKER_RM = 20
RISK_DOCKER_BUILD = 10
RISK_DOCKER_PULL_PUSH = 10
RISK_UNKNOWN_CMD = 10

# Network tools
RISK_NETCAT = 30
RISK_TELNET = 20
RISK_RSYNC = 15
RISK_NMAP = 30
RISK_TCPDUMP = 25

# System administration
RISK_KILL = 30
RISK_SYSTEMCTL = 30
RISK_CRONTAB_EDIT = 40
RISK_CRONTAB_LIST = 0
RISK_PASSWD = 50
RISK_USER_MGMT = 50
RISK_MOUNT = 40
RISK_DISK_MGMT = 80
RISK_IPTABLES = 50

# File tools
RISK_DD = 60
RISK_LN = 10
RISK_LN_FORCE = 20
RISK_TEE = 10
RISK_OPENSSL = 15
RISK_GPG = 10
